name: terraform
on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      DEPLOYERS: |
          [
            "konturn"
          ]
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Terraform fmt
        id: fmt
        uses: dflook/terraform-fmt@976b15307d109bc95a5c0518fd79b9182c17e095 #v1.22.2
        continue-on-error: true
      - name: Terraform Validate
        id: validate
        uses: dflook/terraform-validate@004cb11294aa51f17cddfeda079592a1ae621dc8 #v1.22.2
      - name: Terraform Plan
        if: (${{ github.event.pull_request.head.repo.full_name != github.repository }} && contains( ${{ env.DEPLOYERS }}, ${{ github.event.pusher.name }}) && github.event_name == 'pull_request_target') || (${{ github.event.pull_request.head.repo.full_name == github.repository }} && github.event_name == 'pull_request_target')
        uses: dflook/terraform-plan@1547271e3127df7ad5b667eeed17e8e3a77a76a0 #v1.22.2
        id: plan
        with:
          var_file: |
            vars/tvm-ci-prod.auto.tfvars
          workspace: tvm-ci-prod
